// Generated by CoffeeScript 1.7.1
(function() {
  define(['require', 'cs!jquery', 'angular'], function(require, $, angular) {
    var once, startupFunction, timeout;
    once = function(func) {
      var memo, ran;
      ran = false;
      memo = null;
      return function() {
        if (ran) {
          return memo;
        }
        ran = true;
        memo = func.apply(this, arguments);
        func = null;
        return memo;
      };
    };
    startupFunction = once(function() {
      require(['cs!apps/pteApp', 'cs!controllers/PteCtrl', 'cs!controllers/TableCtrl', 'cs!controllers/CropCtrl', 'cs!controllers/ViewCtrl'], function(pteApp) {
        angular.bootstrap($(".wrap"), [pteApp.name]);
      });
    });
    if (document.readyState === 'complete' || document.readyState === 'loaded') {
      startupFunction();
    } else {
      $(window).load(function() {
        return startupFunction();
      });
    }
    timeout = 10000;
    window.setTimeout(function() {
      return startupFunction();
    }, timeout);
  });

}).call(this);
