// Generated by CoffeeScript 1.7.1
(function() {
  define([], function() {
    var getWindowVar, settings;
    getWindowVar = function(key) {
      if (!window[key]) {
        throw "PTE_EXCEPTION: Invalid window var: " + key;
      }
      return window[key];
    };
    return settings = {
      width: getWindowVar('post_width'),
      height: getWindowVar('post_height'),
      id: getWindowVar('post_id'),
      ajaxurl: getWindowVar('ajaxurl'),
      i18n: getWindowVar('pteI18n'),
      nonce: getWindowVar('pte_nonce'),
      options_nonce: getWindowVar('pte_options_nonce')
    };
  });

}).call(this);
