// Generated by CoffeeScript 1.7.1
(function() {
  (function(jQuery) {
    var $getLink, checkExistingThickbox, image_id, injectPTE, launchPTE, pte_url, timeout;
    timeout = 300;
    image_id = null;
    pte_url = function(override_id) {
      var id;
      id = override_id || image_id || jQuery("#attachment-id").val();
      return _.template(pteL10n.url, {
        'id': id
      });
    };
    $getLink = function(id) {
      return jQuery("<a class=\"thickbox\" href=\"" + (pte_url(id)) + "\">" + pteL10n.PTE + "</a>");
    };
    checkExistingThickbox = function(e) {
      if (window.parent.frames.length > 0) {
        (function(_this) {
          return (function() {
            window.parent.tb_click();
            return true;
          });
        })(this)();
        return e.stopPropagation();
      }
    };
    injectPTE = function() {
      var $editmenu, matches;
      if (imageEdit.open != null) {
        imageEdit.oldopen = imageEdit.open;
        imageEdit.open = function(id, nonce) {
          image_id = id;
          imageEdit.oldopen(id, nonce);
          return launchPTE();
        };
      }
      $editmenu = jQuery("p[id^=\"imgedit-save-target-\"]");
      if (($editmenu != null ? $editmenu.length : void 0) > 0) {
        matches = $editmenu[0].id.match(/imgedit-save-target-(\d+)/);
        if (matches[1] != null) {
          image_id = matches[1];
          launchPTE();
        }
      }
      return true;
    };
    launchPTE = function() {
      var $editmenu, $link, selector;
      selector = "#imgedit-save-target-" + image_id;
      $editmenu = jQuery(selector);
      if (($editmenu != null ? $editmenu.size() : void 0) < 1) {
        window.setTimeout(launchPTE, timeout);
        return false;
      }
      $link = $getLink().click(checkExistingThickbox);
      $link.addClass("button-primary");
      $link.css("margin-top", "10px");
      return $editmenu.append($link);
    };
    return injectPTE();
  })(jQuery);

}).call(this);
