// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular', 'angular-resource', 'cs!apps/urlCacheBreaker'], function(angular) {
    var app;
    app = angular.module('pte', ['ngResource', 'UrlCacheBreaker']);
    return app;
  });

}).call(this);
