// Generated by CoffeeScript 1.7.1
(function() {
  define(['angular'], function(angular) {
    var app;
    app = angular.module('UrlCacheBreaker', []);
    app.filter('randomizeUrl', function() {
      var random, urlMap;
      random = function() {
        return Math.floor(Math.random() * 1000001).toString(16);
      };
      urlMap = {};
      return function(url) {
        var randomness, reset_url, separator, _i, _len, _ref, _ref1;
        if (url == null) {
          return url;
        }
        if ((angular.isObject(url)) && url.reset) {
          if (((_ref = url.urls) != null ? _ref.length : void 0) > 0) {
            _ref1 = url.urls;
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              reset_url = _ref1[_i];
              urlMap[reset_url] = random();
            }
          } else {
            urlMap = {};
          }
          return;
        }
        if (!(url in urlMap)) {
          urlMap[url] = random();
        }
        randomness = urlMap[url];
        separator = '?';
        if ((url != null ? url.indexOf('?') : void 0) >= 0) {
          separator = '&';
        }
        return url + separator + randomness;
      };
    });
    return app;
  });

}).call(this);
