// Generated by CoffeeScript 1.7.1
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['angular', 'cs!apps/pteApp'], function(angular, app) {
    app.controller("TableCtrl", [
      '$scope', function($scope) {

        /*
         * Toggles the selected value from true to false on a row click
         *
         * Ignore the case where the checkbox itself is clicked, This might
         * need to be updated to be useful with the save/cancel icons also
         * found in the table row.
         *
         * @param thumbnail The thumbnail to change
         */
        $scope.toggleSelected = function(thumbnail) {
          thumbnail.selected = !thumbnail.selected;
          $scope.updateSelected();
        };

        /*
         * Used by the view to set all the rows to the same value
         */
        $scope.toggleAll = function() {
          var name, thumbnail, _ref;
          _ref = $scope.thumbnails;
          for (name in _ref) {
            thumbnail = _ref[name];
            thumbnail.selected = $scope.tableSelector;
          }
          $scope.updateSelected();
        };

        /*
         * Toggle the thumbnails based on their aspectRatio
         *
         * If there are multiple thumbnails, use the value of the first thumbnail.selected
         * to determine the rest.
         */
        $scope.selectAspectRatio = function(ar) {
          var selectVal;
          if (typeof event !== "undefined" && event !== null) {
            if (typeof event.stopPropagation === "function") {
              event.stopPropagation();
            }
          }
          selectVal = null;
          angular.forEach($scope.thumbnails, function(thumb) {
            var _ref;
            if (_ref = thumb.name, __indexOf.call(ar.thumbnails, _ref) >= 0) {
              if (selectVal == null) {
                selectVal = (thumb.selected != null) && thumb.selected ? false : true;
              }
              thumb.selected = selectVal;
            }
          });
          $scope.updateSelected();
        };
      }
    ]);
    return app;
  });

}).call(this);
