// Generated by CoffeeScript 1.7.1
(function() {
  define(['cs!apps/pteApp'], function(app) {
    app.controller("ViewCtrl", [
      '$scope', function($scope) {
        $scope.orderBy = function(thumbnail) {
          var current, _ref, _ref1;
          current = ((_ref = thumbnail.current) != null ? _ref.width : void 0) * ((_ref1 = thumbnail.current) != null ? _ref1.height : void 0);
          if ((current != null) && current > 0) {
            return current;
          }
          return thumbnail.width * thumbnail.height;
        };

        /*
         * Click on the picture to select it for cropping and then, change to
         * crop panel
         */
        $scope.selectThumb = function(thumbnail) {
          thumbnail.selected = true;
          $scope.changePage('crop');
          $scope.updateSelected();
        };

        /*
        Add a class to all the thumbnails
           'modified': adds green background
           'original': adds a transition from green to normal (CSS3)
         */
        $scope.thumbnailClass = function(thumbnail) {
          var classes;
          classes = [];
          if (thumbnail.proposed != null) {
            classes.push('modified');
          } else {
            classes.push('original');
          }
          if (thumbnail.selected) {
            classes.push('selected');
          }
          return classes;
        };
      }
    ]);
    return app;
  });

}).call(this);
